//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeartFlame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeartFlame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :x: Unfortunately I&apos;m not sure how long that is. I can support Seconds, Minutes, Hours, Days, Weeks, Months and Years. Please check your spelling and try again..
        /// </summary>
        internal static string BadDuration {
            get {
                return ResourceManager.GetString("BadDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wasn&apos;t the right kind of data.\n
        ///Please make sure to use a hexadecimal color code like FFFFFF.\n
        ///If you typed #FFFFFF please omit the #..
        /// </summary>
        internal static string BadHex {
            get {
                return ResourceManager.GetString("BadHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That wasn&apos;t the right king of data.\n
        ///Please make sure to type an rgb color code like 255 255 255.\n
        ///Make sure to leave a space between each value..
        /// </summary>
        internal static string BadRGB {
            get {
                return ResourceManager.GetString("BadRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 264555514510311424.
        /// </summary>
        internal static string CreatorID {
            get {
                return ResourceManager.GetString("CreatorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :x:Hmm. Is seems this Server has deleted their Join Role or has not set it up. Please set the Join role to a valid Discord Role..
        /// </summary>
        internal static string NoJoinRole {
            get {
                return ResourceManager.GetString("NoJoinRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :x:Uh oh! You do not have permission to do that. You must be at least an admin for the bot to use this command..
        /// </summary>
        internal static string NotAdmin {
            get {
                return ResourceManager.GetString("NotAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :x:Hmm. The chat module has not been enabled. Please contact the bot developer to enable the chat feature if this is in error..
        /// </summary>
        internal static string NotChat {
            get {
                return ResourceManager.GetString("NotChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :x:Hmm. The Username module has not been enabled. Please contact the bot developer to enable the username feature if this is in error..
        /// </summary>
        internal static string NotComp {
            get {
                return ResourceManager.GetString("NotComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :x:You must be the creator of this bot to use this command..
        /// </summary>
        internal static string NotCreator {
            get {
                return ResourceManager.GetString("NotCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :x:Uh oh! You do not have permission to do that. You must have the admin server permission to use this command..
        /// </summary>
        internal static string NotGuildAdmin {
            get {
                return ResourceManager.GetString("NotGuildAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :x:Hmm. The bot logging module has not been enabled. Please contact the bot developer to enable the logging feature if this is in error..
        /// </summary>
        internal static string NotLogging {
            get {
                return ResourceManager.GetString("NotLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :x:Uh oh! You do not have permission to do that. You must be at least a mod for the bot to use this command..
        /// </summary>
        internal static string NotMod {
            get {
                return ResourceManager.GetString("NotMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :x:Hmm. The moderation module has not been enabled. Please contact the bot developer to enable the moderation feature if this is in error..
        /// </summary>
        internal static string NotModeration {
            get {
                return ResourceManager.GetString("NotModeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :x:You must be the owner of the Discord server to use this command..
        /// </summary>
        internal static string NotOwner {
            get {
                return ResourceManager.GetString("NotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :x:Hmm. The permissions module has not been enabled. Please contact the bot developer to enable the permissions feature if this is in error..
        /// </summary>
        internal static string NotPerms {
            get {
                return ResourceManager.GetString("NotPerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :x:Hmm. The self assign module has not been enabled. Please contact the bot developer to enable the self assign feature if this is in error..
        /// </summary>
        internal static string NotSelf {
            get {
                return ResourceManager.GetString("NotSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.patreon.com/heartflamebot.
        /// </summary>
        internal static string PatreonLink {
            get {
                return ResourceManager.GetString("PatreonLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultEndpointsProtocol=https;AccountName=aimbotdata;AccountKey=didJFE0mtpW1vDGWbEe+So8rp9Om2NXbdG4lRp5oBzo7aORz8Rb2tjhbljHiof37QJUlutyEHT8AwcHxXtXEiA==;EndpointSuffix=core.windows.net.
        /// </summary>
        internal static string StorageToken {
            get {
                return ResourceManager.GetString("StorageToken", resourceCulture);
            }
        }
    }
}
